### ISSUE TITLE
TypeError: list indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by AvadheshChoudhary** [informramiz/opencv-face-recognition-python#1]
Preparing data...
Data prepared
Total faces:  23
Total labels:  23
Predicting images...
Traceback (most recent call last):
  File "/Users/avadhesh/Downloads/opencv-face-recognition-python-master/OpenCV-Face-Recognition-Python.py", line 329, in <module>
    predicted_img1 = predict(test_img1)
  File "/Users/avadhesh/Downloads/opencv-face-recognition-python-master/OpenCV-Face-Recognition-Python.py", line 309, in predict
    label_text = subjects[label]
TypeError: list indices must be integers or slices, not tuple

Process finished with exit code 1

**Comment by Clanatia** [comment]
'label' is two value-> (1, 0.0) 

first value is subjects label text count ,
 second is.. I don't know.

so I change like this -> label_text = subjects[label[0]]

it's work.

**Comment by informramiz** [comment]
Latest versions of OpenCV's [predict](https://github.com/informramiz/opencv-face-recognition-python/blob/master/OpenCV-Face-Recognition-Python.py#L306) function returns a `(label, confidence)` tuple. The first value is the label of the subject identified and the second value is the confidence score for that subject. You can use the confidence to filter out low confidence images as unknown subjects. So @Clanatia is right

changing [following](https://github.com/informramiz/opencv-face-recognition-python/blob/master/OpenCV-Face-Recognition-Python.py#L308)

```
label_text = subjects[label]
```

to 

```
label_text = subjects[label[0]]
```

should work fine on OpenCV versions which give this error.

**Comment by foysalhaque** [comment]
AttributeError                            Traceback (most recent call last)
<ipython-input-78-b9b96e999c4a> in <module>()
----> 1 face_recognizer = cv2.face.createLBPHFaceRecognizer()
      2 

AttributeError: module 'cv2' has no attribute 'face'
Why is this problem occurring?

**Comment by AnneJ17** [comment]
> AttributeError Traceback (most recent call last)
> in ()
> ----> 1 face_recognizer = cv2.face.createLBPHFaceRecognizer()
> 2
> 
> AttributeError: module 'cv2' has no attribute 'face'
> Why is this problem occurring?

Use this instead:
face_recognizer = cv2.face.LBPHFaceRecognizer_create()

**Comment by shashanks33** [comment]
> AttributeError Traceback (most recent call last)
> in ()
> ----> 1 face_recognizer = cv2.face.createLBPHFaceRecognizer()
> 2
> 
> AttributeError: module 'cv2' has no attribute 'face'
> Why is this problem occurring?

Try to install opencv using: python -m pip install --user opencv-contrib-python
And then try cv2.face.HBPHFaceRecognizer_create()
